spring.application.name=e-commerce

spring.jpa.open-in-view=false
logging.level.org.springframework.security=DEBUG

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

api.security.token.secret=${JWT_SECURITY_TOKEN}

stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}
stripe.success-url=${STRIPE_SUCCESS_URL}
stripe.failure-url=${STRIPE_FAILURE_URL}

melhorenvio.base-url=${MELHOR_ENVIO_BASE_URL}
melhorenvio.token=${MELHOR_ENVIO_TOKEN}
melhorenvio.app-email=${MELHOR_ENVIO_APP_EMAIL}
melhorenvio.webhook-secret=${MELHOR_ENVIO_WEBHOOK_SECRET}
melhorenvio.from-postal-code=${STORE_POSTAL_CODE}

melhorenvio.store-name=${STORE_NAME}
melhorenvio.store-email=${STORE_EMAIL}
melhorenvio.store-phone=${STORE_PHONE}
melhorenvio.store-address=${STORE_ADDRESS}
melhorenvio.store-number=${STORE_NUMBER}
melhorenvio.store-document=${STORE_DOCUMENT}
melhorenvio.store-district=${STORE_DISTRICT}
melhorenvio.store-city=${STORE_CITY}
melhorenvio.store-state=${STORE_STATE}

spring.mail.host=smtp.gmail.com
spring.mail.port=${MAIL_PORT}
spring.mail.username=${USER_EMAIL}
spring.mail.password=${USER_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jackson.serialization.write-dates-as-timestamps=false

logging.level.root=INFO
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true