spring.application.name=e-commerce

spring.jpa.open-in-view=false

spring.datasource.url=jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}?useSSL=false
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

api.security.token.secret=${JWT_SECURITY_TOKEN}

stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}
stripe.success-url=http://localhost:8080/checkout/success
stripe.failure-url=http://localhost:8080/checkout/failure

melhorenvio.base-url=https://sandbox.melhorenvio.com.br/api/v2
melhorenvio.token=${MELHOR_ENVIO_TOKEN}
melhorenvio.app-email=${MELHOR_ENVIO_APP_EMAIL}
melhorenvio.webhook-secret=${MELHOR_ENVIO_WEBHOOK_SECRET}
melhorenvio.from-postal-code=${STORE_POSTAL_CODE}

spring.mail.host=smtp.gmail.com
spring.mail.port=${MAIL_PORT}
spring.mail.username=${USER_EMAIL}
spring.mail.password=${USER_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.root=INFO
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true