spring.application.name=e-commerce

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce?useSSL=false
spring.datasource.username=root
spring.datasource.password=arthur0702

spring.jpa.open-in-view=false

api.security.token.secret=${JWT_SECRET:my-secret-key}

